name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Registry
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0          
    - name: Build the Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile --tag adamkpn/examtopics-scraper:$(date +%Y%m) --tag adamkpn/examtopics-scraper:latest --push .
